version: '3'

services:
  db:
    image: mysql:latest
    volumes:
     - ./myqsl:/var/lib/mysql
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=qaprosoft
     - MYSQL_DATABASE=argon
     - MYSQL_USER=argon
     - MYSQL_PASSWORD=argon
    restart: always
